### ISSUE TITLE
Nothirium 0.3.1+ is incompatible with LiteLoader

### ISSUE THREAD

**Issue by Felix14-v2** [Meldexun/Nothirium#73]
**Description**
When trying to launch Minecraft with LiteLoader and Nothirium 0.3.1+ Minecraft can't even create a window. Nothirium 0.2.4 works fine.

**To reproduce**
- Install Mixin booting mod ([MixinBootstrap](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap) or [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter))
- Install [RenderLib](https://www.curseforge.com/minecraft/mc-mods/renderlib)
- Install [Nothirium](https://www.curseforge.com/minecraft/mc-mods/nothirium) 0.3.1 or above
- Install [LiteLoader](https://www.liteloader.com/download#snapshot_11220) (as a mod, even without litemods)
- Launch the game
- See the problem – game crashes even before creating a window.
- [x] I can constantly reproduce this issue with a few other mods as possible installed.

**Logs**
<details>
 <summary>latest.log</summary>

```
[19:27:28] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:27:28] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:27:28] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:27:28] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[19:27:28] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Александр\AppData\Roaming\.tlauncher\jre\jre-legacy\windows-x64\jre-legacy
[19:27:28] [main/INFO] [FML]: Searching C:\Users\Александр\AppData\Roaming\.minecraft\home\Forge 1.12.2\mods for mods
[19:27:28] [main/INFO] [FML]: Searching C:\Users\Александр\AppData\Roaming\.minecraft\home\Forge 1.12.2\mods\1.12.2 for mods
[19:27:28] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from !mixinbooter-8.3.jar
[19:27:28] [main/INFO] [FML]: Loading tweaker com.mumfrey.liteloader.launch.LiteLoaderTweaker from liteloader-1.12.2-SNAPSHOT-release.jar
[19:27:28] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Nothirium-1.12.2-0.3.2-beta.jar
[19:27:28] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from RenderLib-1.12.2-1.2.7.jar
[19:27:28] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:27:28] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[19:27:28] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Александр/AppData/Roaming/.minecraft/home/Forge%201.12.2/mods/!mixinbooter-8.3.jar Service=LaunchWrapper Env=CLIENT
[19:27:28] [main/WARN] [FML]: The coremod zone.rong.mixinbooter.MixinBooterPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:27:28] [main/WARN] [FML]: The coremod MixinBooter (zone.rong.mixinbooter.MixinBooterPlugin) is not signed!
[19:27:28] [main/INFO] [MixinBooter]: Initializing Mixins...
[19:27:28] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[19:27:28] [main/INFO] [MixinBooter]: Initializing MixinExtras...
[19:27:29] [main/WARN] [FML]: The coremod NothiriumPlugin (meldexun.nothirium.mc.asm.NothiriumPlugin) is not signed!
[19:27:29] [main/WARN] [FML]: The coremod RenderLibPlugin (meldexun.renderlib.asm.RenderLibPlugin) is not signed!
[19:27:29] [main/INFO] [LaunchWrapper]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[19:27:29] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[19:27:29] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[19:27:29] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:27:29] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:27:29] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:27:29] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:27:30] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[19:27:30] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[19:27:30] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:27:30] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[19:27:30] [main/INFO] [mixin]: Lazily initialising Mixin FML Remapper Adapter
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: meldexun/asmutil2/HashMapClassNodeClassTransformer
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.AccessController.doPrivileged(Native Method)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at $wrapper.meldexun.nothirium.mc.asm.NothiriumClassTransformer.<init>(Unknown Source)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:442)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.inject(MixinPlatformAgentFMLLegacy.java:320)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinContainer.inject(MixinContainer.java:143)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTweaker.injectIntoClassLoader(MixinTweaker.java:64)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: meldexun.asmutil2.HashMapClassNodeClassTransformer
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:27:30] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 28 more
[19:27:30] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[19:27:30] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[19:27:30] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 30 more
```
</details>

[latest.log](https://github.com/Meldexun/Nothirium/files/11970335/latest.log)
~[crash-2023-07-06_18.55.18-client.txt](https://github.com/Meldexun/Nothirium/files/11970336/crash-2023-07-06_18.55.18-client.txt)~

**Versions**
Nothirium: 0.3.1+
RenderLib: 1.2.7+
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): LiteLoader

**Hardware**
CPU: i5 8300H
RAM: 16Gb
GPU: GTX 1050, 536.23
VRAM: 4Gb

**Comment by hampop** [comment]
in your crash report is says you have nothirium  0.2.3-beta

**Comment by Felix14-v2** [comment]
Oh, than there's even no crash report, cuz I just uploaded latest report

**Comment by hampop** [comment]
and you need RenderLib 1.3.1 to run Nothirium: 0.3.1+

**Comment by Felix14-v2** [comment]
Well, I tested different combinations, RenderLib 1.3.1 also didn't work for me. Will test again

**Comment by Meldexun** [comment]
As hampop said you need RenderLib 1.3.1 to run Nothirium 0.3.1

If there still is an issue with liteloader you can reopen this issue.
