### ISSUE TITLE
Crash with LoliASM

### ISSUE THREAD

**Issue by Kasia1403** [Meldexun/Nothirium#89]
[crash-2023-11-22_11.54.52-client.txt](https://github.com/Meldexun/Nothirium/files/13438705/crash-2023-11-22_11.54.52-client.txt)

**Comment by Kasia1403** [comment]
Why unconfirmed ?

**Comment by ZZZank** [comment]
I think it is not nothirium's issue, see these lines: 
```
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.remove(Unknown Source)
    at net.minecraft.client.audio.SoundManager.updateAllSounds(SoundManager.java:309)
    at net.minecraft.client.audio.SoundHandler.update(SoundHandler.java:293)
```

This indicates that Sound Engine is related to the crash, but neither Nothirium nor LoliASM modifies SoundEngine. `dsurround` is more likely to be the troublemaker
